//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiNa_Deploy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>.bat|cmd.exe|</string>
  <string>.cab|dism.exe|/online /add-package /packagepath:#PACKAGE</string>
  <string>.cmd|cmd.exe|/C #PACKAGE</string>
  <string>.exe||</string>
  <string>.msi|msiexec.exe|/i #PACKAGE /quiet /norestart</string>
  <string>.msp|msiexec.exe|/p #PACKAGE /quiet /norestart</string>
  <string>.msu|wusa.exe|#PACKAGE /quiet /norestart</string>
  <string>.ps1|powershell.exe|-file #PACKAGE -verb runas</string>
  <string>.reg|reg32.exe|/s #PACKAGE</string>
  <string>.vbs|cscript.exe|#PACKAGE</string>
  <string>Custom</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FileExtensions"]));
            }
            set {
                this["FileExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Windows\\Temp\\NiNa")]
        public string TempLocation {
            get {
                return ((string)(this["TempLocation"]));
            }
            set {
                this["TempLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int PingTimeout {
            get {
                return ((int)(this["PingTimeout"]));
            }
            set {
                this["PingTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PsExecLocation {
            get {
                return ((string)(this["PsExecLocation"]));
            }
            set {
                this["PsExecLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxPsExecProcs {
            get {
                return ((int)(this["MaxPsExecProcs"]));
            }
            set {
                this["MaxPsExecProcs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int PsExecInterval {
            get {
                return ((int)(this["PsExecInterval"]));
            }
            set {
                this["PsExecInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PsExecAsSystem {
            get {
                return ((bool)(this["PsExecAsSystem"]));
            }
            set {
                this["PsExecAsSystem"] = value;
            }
        }
    }
}
